### ISSUE TITLE
cant run the install.sh script without errors

### ISSUE THREAD

**Issue by Shakatakshakatak** [LBRYFoundation/pool#16]
Hi, when i try to install the install.sh script, i cant, i got this :   ( on clean ubuntu 18.04 fresh updated ) 

./install.sh: line 859: unexpected EOF while looking for matching `"'
./install.sh: line 860: syntax error: unexpected end of file

**Comment by marko-lorentz** [comment]
There were some minor flaws in the script. I will try to send a PR with an improved version later this day (after another test run on a clean VM snapshot).
My goal was to make it work on Ubuntu 18.04(.5) Server LTS.

**Comment by marko-lorentz** [comment]
PR is available now - see #17

**Comment by marko-lorentz** [comment]
Addendum:

**Daemon behavior**
The installer starts `lbrycrdd` for some seconds in order to generate the file/folder structure required in `~/..lbrycrd` - see near line 863:
```
lbrycrdd -daemon -server
sleep 3
lbrycrd-cli stop
```
This will only work when the daemon has never been started before. It it was running before, the daemon process will be stuck in the initialisation phase (e.g. claim trie checking) that can take up to some minutes and therefore ignore the `lbrycrd-cli stop` command. This again will not allow proper restart after replacing the config file in line 911 of the script. The daemon will then continue run with the wrong config and needs a manual restart.
I think I will extend the PR to include a check whether the folder already exists and skip the initial startup in this case.

**Coin configuration**
The main `README.md` that describes how to configure the LBRY coin didn't work for me. As the coin was not available in the initial coin list, I had to create it. I addition to the instructions given, you have to set the correct RPC port (14390) and switch the settings for 
* `Has getinfo` to "false" as `lbrycrd-cli` does no longer support this command and
* `Use segwit` to "true" as is is required now (seeing Stratum errors like `lbry dead lock, exiting...` might indicate you missed this one).

I propose to edit the README and I will check whether it makes sense to create the coin using an SQL script that does it during the initial setup phase of the MySQL database.

**Comment by Coolguy3289** [comment]
I will merge this PR now @marko-lorentz . As for the lbrycrdd issue, we could instead issue a killall for lbrycrdd instead. It's a hard-kill, which may cause claimtrie or db corruption, but if we add steps into the script to automatically remove any of the usual folders except for the config, this may be a better blanket solution to ensure the daemon is stopped and the install script can ensure it's on the correct config.

**Comment by andrasmining** [comment]
thanks! I sent you an FR on discord. Can we have a DM?

**Comment by marko-lorentz** [comment]
I will have a look at the script again and check for further errors.

Checked: Script was ok - problem with `wget` broke it.
